{% set version = "2.24.0" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: 4e6f99e0a5579bbbc32e449c4dbb039561d4f1a7827d5733273ed56738f21f07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - hatchling >=1.5
    - pip
    - python >=3.7

  run:
    - babel >=2.10
    - importlib-metadata >=4.8.3
    - jinja2 >=3.0.3
    - json5 >=0.9.0
    - jsonschema >=4.17.3
    - jupyter_server >=1.21,<3
    - packaging >=21.3
    - python >=3.7
    - requests >=2.28

test:
  source_files:
    - tests
    - jupyterlab_server/test_data
  requires:
    - ipykernel
    - openapi-core >=0.16.1,<0.17.0
    - openapi-spec-validator >=0.5.1,<0.7.0
    - pip
    - pytest >=7.0
    - pytest-console-scripts
    - pytest-cov
    - pytest-jupyter-server >=0.6.2
    - pytest-timeout
    - requests-mock
    - ruamel.yaml
    - strict-rfc3339
    - werkzeug
  imports:
    - jupyterlab_server
  commands:
    - pip check
    - cd tests && pytest -vv --cov=jupyterlab_server --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=85
  downstreams:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  doc_url: https://jupyterlab-server.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
