{% set version = "2.5.0" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: 4c2c482cc91b7439ea5415f8f85ded95059fb9cdab03f5f0e6338246830c2a5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - jupyter-packaging >=0.9,<1
    - jupyter_server
    - pip

  run:
    - python >=3.6
    - babel
    - jinja2 >=2.10
    - json5
    - jsonschema >=3.0.1
    - jupyter_server >=1.4,<2
    - jupyter-packaging >=0.9,<2
    - packaging
    - requests

test:
  requires:
    - pip
  imports:
    - jupyterlab_server
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
